#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

sudo ln -sv $SCRIPT_DIR /var/db/repos/
sudo mkdir /etc/portage/repos.conf
echo $'[beef-layer]\nlocation = /var/db/repos/beef-layer' | sudo tee /etc/portage/repos.conf/beef-layer.conf
